version: '2'
services:
    fuscone-app:
        image: fuscone
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fuscone-postgresql:5432/fuscone
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=fuscone-elasticsearch:9300
        ports:
            - 8080:8080
    fuscone-postgresql:
        extends:
            file: postgresql.yml
            service: fuscone-postgresql
    fuscone-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: fuscone-elasticsearch
